### PR TITLE
ok

### PR DESCRIPTION
**Pull request by CST44**
ok

### CODE REVIEW

**Comment by CST44** [comment]
ss

**Comment by ajp-io** [comment]
Hi, @CST44. If you want to make changes to this repo for the lab or for your own experimentation, you should fork this repository and make changes to your own copy. This repo needs to remain as it is. [Here](https://docs.github.com/en/github/getting-started-with-github/fork-a-repo) are instructions on forking. Let me know if you have questions.

**Comment by alexparker215** [comment]
Hi, @CST44. I cannot accept this pull request since this repo needs to be used by all users. You can commit to your own fork and make changes there. Thanks!

**Comment by CST44** [comment]
Ok, sorry for thatRegards / CordialementCharles SterchiIBM Expert Technique JDE+33 6 62 35 09 82-----Alex Parker <notifications@github.com> a écrit : -----A : ajp-io/serverless-guestbook <serverless-guestbook@noreply.github.com>De : Alex Parker <notifications@github.com>Date : 06/03/2021 00:33Cc: CST44 <charles.sterchi@fr.ibm.com>, Mention <mention@noreply.github.com>Objet : [EXTERNAL] Re: [ajp-io/serverless-guestbook] ok (#1)




Hi, @CST44. I cannot accept this pull request since this repo needs to be used by all users. You can commit to your own fork and make changes there. Thanks!

**Comment by alexparker215** [comment]
No worries at all! Thanks.

**Pull request closed without merging**
